<link href="../../../../application/public/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<!-- Custom styles for this template -->
<link href="../../../../application/public/assets/css/signin.css" rel="stylesheet">

<main class="form-signup text-center d-flex justify-content-center">
    <form action="" method="post">
        <h1 class="h3 mb-3 fw-normal">Add New Product</h1>
        <div class="form-floating">
            <input type="text" class="form-control" id="floatingUname" name="name" required>
            <label for="floatingPassword">Name</label>
        </div>
        <div class="form-floating">
            <input type="text" class="form-control" id="floatingEmail" name="price" required>
            <label for="floatingInput">Price</label>
        </div>
        <div class="form-floating">
            <input type="text" class="form-control m-0" id="floatingPassword" name="stock" required>
            <label for="floatingPassword">Stock</label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" name="add" type="submit">Add Product</button>
        <p class="mt-5 mb-3 text-muted">&copy; CEDCOSS Technologies</p>
    </form>
</main>