<?php include('header.phtml'); ?>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center
         pt-3 pb-2 mb-3 border-bottom">
    </div>

    <h2>Products</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th scope="col">Product Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Stock</th>
                    <th scope="col">EDIT</th>
                    <th scope="col">DELETE</th>
                </tr>
            </thead>
            <tbody>

                <?php
                foreach ($products as $k => $v) {
                ?>
                    <tr>
                        <td><?php echo $v["_id"] ?></td>
                        <td><?php echo $v['name']  ?></td>
                        <td><?php echo $v['price']  ?></td>
                        <td><?php echo $v['stock']  ?></td>
                        <td><a class="btn btn-primary" href="updateProd?id=<?php echo $v["_id"] ?>">EDIT</a></td>
                        <td><a class="btn btn-danger" href="deleteProd?id=<?php echo $v["_id"] ?>">DELETE</a></td>
                    <?php  }
                    ?>
            </tbody>
        </table>
    </div>
    <?php echo $this->tag->linkTo(
        [
            "application/admin/addProduct",
            "Add Product",
            "class" => "btn btn-success"
        ]
    ); ?>

</main>
</div>
</div>
</body>