<link href="../../../../application/public/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<!-- Custom styles for this template -->
<link href="../../../../application/public/assets/css/signin.css" rel="stylesheet">

<main class="form-signup text-center d-flex justify-content-center">
    <form action="" method="post">
        <h1 class="h3 mb-3 fw-normal">Add WebHook</h1>
        <div class="form-floating">
            <input type="text" class="form-control" id="floatingUname" name="WebHook" required>
            <label for="floatingPassword">WebHook Name</label>
        </div>
        <div class="form-floating">
            <input type="text" class="form-control" id="floatingUname" name="url" required>
            <label for="floatingPassword">URL</label>
        </div>
        <div class="form-floating">
            <p>Select Events</p>
            <p><input type="checkbox" name="action[]" value="update"> Update Product
                <input type="checkbox" name="action[]" value="create"> Create Product
                <input type="checkbox" name="action[]" value="delete"> Delete Product
            </p>

        </div>
        <div class="form-floating">
            <input type="text" class="form-control m-0" id="floatingPassword" name="key" required>
            <label for="floatingPassword">Secret Key</label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" name="addWeb" type="submit">Add WebHook</button>


    </form>
</main>

<div class="d-flex justify-content-center">
    <p>Hey Developer! Waana see all products
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="red" class="bi bi-emoji-wink" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
            <path d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm1.757-.437a.5.5 0 0 1 .68.194.934.934 0 0 0 .813.493c.339 0 .645-.19.813-.493a.5.5 0 1 1 .874.486A1.934 1.934 0 0 1 10.25 7.75c-.73 0-1.356-.412-1.687-1.007a.5.5 0 0 1 .194-.68z" />
        </svg>
    </p>
    <br>
    <p>
        <a href="http://<?php echo $_SERVER["HTTP_HOST"] ?>/frontend/index">Click Me</a>
    </p>

</div>